Change sha1 to sha265
It appears sha1 is deprecated:

$ brew upgrade
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/8bitsofme/homebrew-msp430/msp430-elf-gcc.rb:8:in `<class:Msp430ElfGcc>'
Please report this to the 8bitsofme/msp430 tap!